[env:nucleo_g474re]
platform = ststm32
board = nucleo_g474re
framework = arduino
monitor_speed = 115200
upload_protocol = stlink
lib_deps =
    ; No external libs needed – Wire.h and Serial are built-in
build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
